import type { NextConfig } from "next";
const staticExport = Boolean(process.env.PAGES_BASE_PATH);
const config: NextConfig = {
  // Keep repository guidance authored here instead of regenerated by next dev.
  agentRules: false,
  // Static hosting exports UI entries only; .ts API routes require the Node server.
  pageExtensions: staticExport ? ["tsx", "jsx"] : ["tsx", "ts", "jsx", "js"],
  serverExternalPackages: ["node:sqlite"],
  // Static export for GitHub Pages. The workflow sets PAGES_BASE_PATH to the
  // repository's base path (e.g. "/apsis") so assets resolve under the Pages
  // subpath. When unset (local `next dev` / `next build`), the app runs at the
  // root with the full server (SQLite + API routes) intact.
  ...(staticExport ? { output: "export" as const } : {}),
  basePath: process.env.PAGES_BASE_PATH || undefined,
  trailingSlash: staticExport,
};
export default config;
