import { defineCourse } from "@/prefabs/authoring";
import course from "./course.json";
import inspect from "./lessons/inspect-a-run.json";
import models from "./lessons/model-behaviour.json";
import selection from "./lessons/model-selection.json";
import context from "./lessons/context-design.json";
import tools from "./lessons/usable-tools.json";
import mcp from "./lessons/mcp.json";
import skills from "./lessons/skills.json";
import harness from "./lessons/harness.json";
import recovery from "./lessons/recovery.json";
import workflows from "./lessons/workflow-shapes.json";
import firstAw from "./lessons/first-gh-aw.json";
import authority from "./lessons/bounded-authority.json";
import recurring from "./lessons/recurring-work.json";
import connected from "./lessons/workflow-capabilities.json";
import diagnose from "./lessons/diagnose-runs.json";
import outcomes from "./lessons/useful-outcomes.json";

export default defineCourse({ ...course, topics: [inspect, models, selection, context, tools, mcp, skills, harness, recovery, workflows, firstAw, authority, recurring, connected, diagnose, outcomes] });
