import type { Chapter } from "../chapter";
import { numeric, choice } from "@/curriculum-support/authoring";

const chapter: Chapter = {
  id: "two-body",
  theoreticalMinimum: {coreIdea:"Conservation laws remove variables from a dynamical problem. Relative coordinates turn two attracting bodies into one radial energy problem plus an angular clock.", widerConnection:"The effective potential turns orbital stability into the curvature test already used for oscillators. Changing from radius to inverse radius reveals a linear oscillator hidden inside nonlinear orbital motion."},
  intuition:{body:"Watch two skaters pull on opposite ends of a rope. Both move, yet their common centre of mass can remain still. Gravitational attraction behaves similarly: even a planet's star moves. The useful question is which parts of this motion need solving separately.\n\nWe will separate the common drift from the changing separation, then use angular momentum and energy to simplify what remains. An orbit is an especially rich meeting place for coordinates, integration and differential equations: choosing the right variable can turn a difficult-looking curve into a familiar oscillator.",thoughtExperiments:["If both masses double, does their relative acceleration stay the same?","Can a force that always points inward nevertheless allow a particle to move outward?"]},
  theory:[
    {heading:"1. Separate common motion from relative motion",body:String.raw`Let two isolated point masses have positions $\mathbf r_1,\mathbf r_2$, and put $M=m_1+m_2$. Define their centre of mass and separation by
$$\mathbf R=\frac{m_1\mathbf r_1+m_2\mathbf r_2}{M},\qquad \mathbf r=\mathbf r_2-\mathbf r_1.$$
These are new coordinates for exactly the same six position numbers. Recovering the original positions gives $\mathbf r_1=\mathbf R-(m_2/M)\mathbf r$ and $\mathbf r_2=\mathbf R+(m_1/M)\mathbf r$. The more massive body stays closer to the centre; equal masses move equally far from it.

Internal forces are equal and opposite, so adding Newton's equations gives $M\ddot{\mathbf R}=0$. The centre drifts uniformly. Subtracting the acceleration equations for Newtonian gravity instead gives
$$\ddot{\mathbf r}=-\frac{G(m_1+m_2)}{r^3}\mathbf r=-\frac{\mathcal G}{r^3}\mathbf r,$$
where $\mathcal G=GM$ is the gravitational parameter. Both bodies accelerate toward each other, which is why the sum of their masses appears. Treating the heavier body as fixed is an approximation valid when the other mass is negligible.

The energy also separates. Substitute the two velocities into their total kinetic energy and expand the dot products. The cross terms cancel because $m_1(m_2/M)=m_2(m_1/M)$, leaving
$$K=\tfrac12M\dot{\mathbf R}^{\,2}+\tfrac12\mu\dot{\mathbf r}^{\,2},\qquad \mu=\frac{m_1m_2}{M}.$$
The reduced mass $\mu$ is the inertia attached to the separation coordinate. It is not another gravitating object. Multiplying the relative acceleration equation by $\mu$ recovers the force magnitude $Gm_1m_2/r^2$ because $\mu M=m_1m_2$.

This is a useful general lesson about coordinate choice. A coupled-looking problem can contain an independently evolving part that disappears once we describe it appropriately. We have not approximated the two-body system; we have found coordinates in which one part is already solved. The remaining initial data are relative position and relative velocity, which still contain the full information about the internal orbit.`},
    {heading:"2. Angular momentum converts turning into a radial energy term",body:String.raw`The relative force points along $\mathbf r$, so its torque about the relative origin is zero. Differentiate $\mathbf h=\mathbf r\times\dot{\mathbf r}$: the velocity crossed with itself vanishes, and $\mathbf r\times\ddot{\mathbf r}=0$. Thus $\mathbf h$ is a constant vector. Unless it is zero, motion stays in the plane perpendicular to it. In that plane choose polar coordinates and write $h=r^2\dot\theta$ with positive orientation along $\mathbf h$.

This is the same conservation law obtained from polar tangential acceleration in the trajectories chapter. It says angular speed changes when radius changes: a smaller radius demands a faster sweep. The small triangular area swept in time $dt$ is $r^2d\theta/2$, so equal times sweep equal areas. Geometry has translated a conserved quantity into an observable rule.

Dot the relative acceleration with velocity. The left side is the derivative of $\dot{\mathbf r}^{\,2}/2$, and the gravitational work integrates to potential $-\mathcal G/r$. The conserved relative energy per reduced mass is therefore
$$\varepsilon=\tfrac12\dot r^2+\frac{h^2}{2r^2}-\frac{\mathcal G}{r}=\tfrac12\dot r^2+V_{\rm eff}(r).$$
The effective potential $V_{\rm eff}=h^2/(2r^2)-\mathcal G/r$ includes the tangential kinetic energy. It is bookkeeping, not a new fundamental outward force. Holding angular momentum fixed makes that kinetic energy rise sharply as the radius shrinks.

Allowed radii satisfy $\varepsilon\ge V_{\rm eff}$ because radial kinetic energy cannot be negative. Equality identifies a radial turning point, where radial velocity vanishes but tangential velocity usually does not. Negative energy confines a noncollisional orbit between two radii; nonnegative energy can allow escape to infinity. These statements presume the inverse-square potential with zero chosen at infinity.

Once a branch is chosen, $\dot r=\pm\sqrt{2(\varepsilon-V_{\rm eff})}$ is a first-order equation. Its integral supplies elapsed time; integrating $\dot\theta=h/r^2$ supplies angle. Conservation has reduced the order of the dynamical problem, but it has not supplied the initial phase or selected the inward versus outward branch.`},
    {heading:"3. A circular orbit is a minimum, and its disturbance is an oscillator",body:String.raw`A constant radius must satisfy $V_{\rm eff}'(r_c)=0$. Differentiating gives $-h^2/r_c^3+\mathcal G/r_c^2=0$, hence $r_c=h^2/\mathcal G$. At this radius the circular angular frequency is $\Omega=h/r_c^2=\sqrt{\mathcal G/r_c^3}$.

Now ask a deeper question than whether circular motion exists: what happens after a small radial disturbance? Hold h fixed and write $r=r_c+\xi$. The exact radial equation is $\ddot r=-V_{\rm eff}'(r)$. Taylor expansion at the stationary point gives
$$\ddot\xi\simeq-V_{\rm eff}''(r_c)\xi,\qquad V_{\rm eff}''(r_c)=\frac{\mathcal G}{r_c^3}>0.$$
The disturbance is a harmonic oscillator with frequency $\kappa=\Omega$. A minimum supplies a restoring acceleration; the second derivative tells us its strength. This is the oscillator chapter's curvature argument, now applied to an orbit rather than a spring.

Be careful about what was held constant. A radial kick leaves h unchanged, but a tangential kick changes it and therefore changes the reference circular radius. Stability means nearby solutions remain nearby in the relevant dynamical sense; it does not mean every perturbed particle returns to its original point at its original time. A conservative system has no mechanism that makes disturbances decay.

For a general central potential per mass V(r), the same calculation gives $V_{\rm eff}=V+h^2/(2r^2)$ and, at a circular orbit,
$$\Omega^2=\frac{V'(r_c)}{r_c},\qquad \kappa^2=V''(r_c)+\frac{3V'(r_c)}{r_c}.$$
These two frequencies need not agree. Between successive closest approaches, a nearly circular orbit advances approximately $2\pi\Omega/\kappa$. If that differs from a full turn, the closest-approach direction moves. Thus a small change of force law can create precession. This connection is a powerful use of local approximation: potential curvature predicts the large-scale orientation change of a nearly circular trajectory.`},
    {heading:"4. An ellipse hides a linear equation in inverse radius",body:String.raw`There is an even more striking simplification for gravity. Assume h is nonzero and use angle as the independent variable. Set $u(\theta)=1/r$ and use a prime for an angular derivative. Because $\dot\theta=hu^2$, the chain rule gives $\dot r=-hu'$ and $\ddot r=-h^2u^2u''$. Substitution into the polar radial equation $\ddot r-r\dot\theta^2=-\mathcal G/r^2$ yields
$$u''+u=\frac{\mathcal G}{h^2}.$$
The original motion was nonlinear in Cartesian coordinates and in time. In inverse radius as a function of angle, it is a forced linear oscillator with constant forcing. The transformation did not make time run uniformly with angle; it chose a variable suited to the geometric question.

The solution is $u=(\mathcal G/h^2)[1+e\cos(\theta-\theta_0)]$, so
$$r=\frac{p}{1+e\cos(\theta-\theta_0)},\qquad p=\frac{h^2}{\mathcal G}.$$
Here $\theta_0$ sets the direction of closest approach and $e\ge0$ measures the departure from circularity. Substituting this solution into the energy relation gives $e^2=1+2\varepsilon h^2/\mathcal G^2$. For negative energy, $0\le e<1$ and the conic is an ellipse; at zero energy it is a parabola; for positive energy it is a hyperbola on the physically allowed angular range.

Notice what the calculation teaches beyond the orbit formula. Linearity is sometimes a property revealed by a representation, rather than something obvious in the original equation. But the representation has conditions: purely radial motion has h=0 and cannot use angle as a clock. Likewise, the conic describes the path, while recovering the position at a specified time still requires $dt=r^2d\theta/h$. Keeping geometry and timing separate prevents an elegant solution from answering more than it actually does.`},
  ],
  teaching:{question:"How much of an orbit can conservation and a change of coordinates solve?",why:"One physical problem connects moving bases, energy integrals, effective potentials and linear oscillators.",outcomes:["Separate centre-of-mass and relative motion.","Use energy and angular momentum to identify allowed radii.","Derive circular stability and the inverse-radius orbit equation."],checkpoints:[
    {bridge:"Separate the common drift.",meaning:"Relative coordinates have a different effective inertia.",question:"Why does relative gravitational acceleration contain the sum of masses?",answer:"Both bodies accelerate toward one another, so subtracting their accelerations adds their magnitudes.",further:[{question:"What is the reduced mass?",answer:"m₁m₂/(m₁+m₂)."},{question:"When can one body be treated as fixed?",answer:"Approximately when its mass greatly exceeds the other's."},{question:"What removes the kinetic-energy cross term?",answer:"The mass-weighted centre-of-mass definition."}]},
    {bridge:"Replace angular speed with conserved angular momentum.",meaning:"Tangential kinetic energy becomes a function of radius.",question:"Does a radial turning point mean the particle stops?",answer:"No; only radial velocity vanishes. Tangential motion can continue.",further:[{question:"What fixes the swept-area rate?",answer:"Half the conserved h."},{question:"Why are radii with Veff greater than energy forbidden?",answer:"They would require negative radial kinetic energy."},{question:"Does energy alone pick the direction of radial motion?",answer:"No; the sign of radial velocity also matters."}]},
    {bridge:"Expand about circular motion.",meaning:"Curvature supplies the restoring coefficient.",question:"Does stable circular motion damp a radial disturbance?",answer:"No; stability and damping are different. The conservative disturbance oscillates.",further:[{question:"What is held fixed in the radial effective potential?",answer:"Angular momentum h."},{question:"What does negative second derivative predict?",answer:"Local radial instability."},{question:"What can unequal radial and angular frequencies produce?",answer:"Precession of the closest-approach direction."}]},
    {bridge:"Let angle track inverse radius.",meaning:"A nonlinear motion contains a linear geometric equation.",question:"Does the conic formula give position as a function of time?",answer:"No; time follows from integrating r²/h against angle.",further:[{question:"Why exclude h=0 from this derivation?",answer:"Angle then cannot serve as the evolving variable."},{question:"What does e=0 describe?",answer:"A circle."},{question:"Why is inverse radius a useful representation?",answer:"It turns the inverse-square central-force orbit equation into u''+u=constant."}]}
  ],takeaway:"The right coordinates expose conserved quantities; conserved quantities expose simpler equations.",nextConnection:"Perturbation asks how these exact structures change when the force or oscillation is only approximately ideal."},
  workedExample:{title:"Read an orbit from one instant",problem:"In scaled units let the gravitational parameter be 1, radius be 1, radial velocity be 0 and tangential speed be √(3/2). Find the orbit's energy, eccentricity and extreme radii.",steps:[{title:"Find angular momentum",body:"$h=rv_\theta=\sqrt{3/2}$, so $h^2=3/2$.",reason:"The velocity is entirely tangential at this instant.",trap:"Do not confuse angular momentum with angular speed."},{title:"Compute energy",body:"$\varepsilon=v^2/2-1/r=3/4-1=-1/4$.",reason:"Negative relative energy implies a bound orbit here.",trap:"The potential has a negative sign."},{title:"Find the conic",body:"$p=3/2$ and $e=\sqrt{1+2(-1/4)(3/2)}=1/2$.",reason:"The two conserved scalars determine shape and scale.",trap:"The square root applies to the whole expression."},{title:"Identify the turning points",body:"$r_{\min}=p/(1+e)=1$ and $r_{\max}=p/(1-e)=3$.",reason:"Cosine equal to ±1 gives the extreme radii.",trap:"Zero radial velocity does not distinguish nearest from farthest by itself."},{title:"Check the distant speed",body:"At radius 3, $v_\theta=h/3$, so $v^2=1/6$. Energy is $1/12-1/3=-1/4$ again.",reason:"An independent energy check tests both turning radii.",trap:"Speed is smaller at the more distant turning point."}]},
  diagnostics:[choice("d-polar","For a central force, which polar quantity is constant?",["r² times angular speed","Radial speed","Radius"],0,"Zero tangential acceleration implies d(r²θ̇)/dt=0.","Recall polar acceleration.",{prerequisiteId:"trajectories"}),choice("d-branch","For dr/dt=f(r), what selects a particular solution?",["An initial radius at a specified time","The dimensions alone","Only the name of the variable"],0,"The initial condition selects a trajectory.","Recall a first-order initial-value problem.",{prerequisiteId:"first-order-odes"}),numeric("d-integral","Find the change in −1/r from r=1 to r=2 in scaled units. Enter unit 1.",0.5,"1","−1/2−(−1)=1/2.","Subtract endpoint values.",{prerequisiteId:"integrals"})],
  fadedExercise:{prompt:"Use scaled units with gravitational parameter 2, h²=8 and relative energy −1/8.",supplied:[{heading:"Shape relations",body:String.raw`Use $p=h^2/\mathcal G$, $e^2=1+2\varepsilon h^2/\mathcal G^2$ and $r_{\min,\max}=p/(1\pm e)$.`}],steps:[numeric("f-p","With gravitational parameter 2 and h²=8, find p. Enter unit 1.",4,"1","8/2=4.","Divide angular momentum squared by the gravitational parameter."),numeric("f-e","With gravitational parameter 2, h²=8 and energy −1/8, find e². Enter unit 1.",0.5,"1","1+2(−1/8)8/4=1/2.","Keep the square of the gravitational parameter."),numeric("f-min","For p=4 and e=√(1/2), find the minimum radius. Enter unit 1.",4/(1+Math.sqrt(0.5)),"1","4/(1+√(1/2)).","The largest denominator gives the smallest radius."),choice("f-bound","An inverse-square orbit has energy −1/8 and nonzero angular momentum. Can it reach infinity?",["No","Yes, at zero speed","Yes, at arbitrary speed"],0,"At infinity the potential vanishes, leaving nonnegative kinetic energy, incompatible with negative total energy.","Compare energy with its value at infinity.")]},
  retrievalProblems:[numeric("r-mass","For masses 2 kg and 3 kg, find reduced mass.",1.2,"kg","6/5=1.2 kg.","Multiply masses and divide by their sum."),choice("r-center","For an isolated two-body system, the centre of mass has which acceleration?",["Zero","The larger body's acceleration","Infinite"],0,"Internal forces cancel.","Add Newton's equations."),numeric("r-circle","In scaled units with gravitational parameter 2 and h²=8, find circular radius. Enter unit 1.",4,"1","8/2=4.","Set the effective-potential derivative to zero."),numeric("r-frequency","For gravitational parameter 8 and circular radius 2 in scaled units, find radial small-oscillation frequency. Enter unit 1.",1,"1","√(8/2³)=1.","Use effective-potential curvature."),choice("r-effective","The positive h²/(2r²) term represents what?",["Tangential kinetic energy expressed at fixed h","A new interaction","Dissipation"],0,"Conservation lets us express angular kinetic energy using radius.","Remember where the term came from."),choice("r-linear","Which variable satisfies a linear angular equation in inverse-square gravity?",["Inverse radius","Radius cubed","Elapsed time"],0,"u=1/r satisfies u''+u=G M/h².","Choose the representation derived in the chapter.")]},
  diagram:{title:"Allowed radii between turning points",caption:"For a bound orbit with nonzero angular momentum, radial kinetic energy is the vertical gap between the horizontal energy line and effective potential. Only the interval between intersections is allowed.",viewBox:[0,0,600,320],elements:[{kind:"line",from:[55,270],to:[550,270],tone:"muted"},{kind:"line",from:[55,270],to:[55,25],tone:"muted"},{kind:"path",d:"M 85 30 C 100 155 125 240 210 240 C 300 240 385 140 530 105",tone:"accent"},{kind:"line",from:[65,170],to:[535,170],tone:"ink"},{kind:"label",at:[370,155],text:"fixed negative energy"},{kind:"label",at:[215,260],text:"effective-potential minimum"},{kind:"label",at:[440,295],text:"radius →"},{kind:"label",at:[90,195],text:"inner turn"},{kind:"label",at:[345,195],text:"outer turn"}]},
  sidebars:[{heading:"Why the energy decomposition resembles completing a square",body:String.raw`For scalar velocities the identity $m_1v_1^2+m_2v_2^2=M V^2+\mu(v_2-v_1)^2$ is a weighted version of completing a square. It also resembles the decomposition of total variation into motion of a mean and variation around that mean. Each Cartesian component obeys the same identity, so the vector result follows by addition. The mass weights choose the particular mean that cancels the cross term. This is a small example of diagonalising a quadratic form: choosing coordinates that remove mixed terms. Later, normal modes will use the same strategy to separate coupled oscillators.`}],
  sources:[]
};
export default chapter;
